spring:
  mvc:
    format:
      date: dd/MM/yyyy
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/attraction
    username: rootuser
    password: trust
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  flyway:
    user: rootuser
    password: trust
    schemas: public
    validate-on-migrate: true
    baseline-on-migrate: true
jwt:
  secret: secret
  time-life: 30